name: Warmup Render

on:
  schedule:
    - cron: "10,15,20,25 11 * * 2"

  workflow_dispatch:

jobs:

  warmup:

    runs-on: ubuntu-latest

    steps:

      - name: Warm Render
        run: |
          curl https://linkedin-content-automation-7e6j.onrender.com/health
          